
language: node_js
addons:
  apt:
    packages:
      - libxtst-dev

node_js: 12

install:
  - npm install

script:
  - npm run lint

cache:
  npm: true
  directories:
    - node_modules

branches:
  only:
    - master
